version: '3'
services:
  freedy:
    image: kolex/freedy:latest
    container_name: freedy
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./urls.txt:/home/freedy/config/urls.txt